### ISSUE TITLE
Please Implement Sysbta HAL. It Is Required For Fixing Bluetooth Crash On Few Devices

### ISSUE THREAD

**Issue by RT1648** [VoltageOS/packages_modules_Bluetooth#1]

**Comment by TheHardGamer** [comment]
@shutter-cat please

**Comment by RT1648** [comment]
> @shutter-cat please

What's wrong with it? Already other roms have implemented it

**Comment by TheHardGamer** [comment]
> > @shutter-cat please
> 
> What's wrong with it? Already other roms have implemented it



Pick it yourself and send a Pull Request

**Comment by shutter-cat** [comment]
> 

and get decline still

**Comment by shutter-cat** [comment]
> > > @shutter-cat please
> > 
> > 
> > What's wrong with it? Already other roms have implemented it
> 
> Pick it yourself and send a Pull Request

and still get declined

**Comment by RT1648** [comment]
> 

I tried to open a pull request but it failed

**Comment by RT1648** [comment]
> 

Please do something for it. Merge it in source

**Comment by TheHardGamer** [comment]
Fork this repo, pick it yourself and give us the link, we will merge it

> > 
> 
> Please do something for it. Merge it in source

**Comment by shutter-cat** [comment]
> Fork this repo, pick it yourself and give us the link, we will merge it
> 
> > > 
> > 
> > 
> > Please do something for it. Merge it in source

none of our devices use that hal, so naaaaah

**Comment by RT1648** [comment]
> Fork this repo, pick it yourself and give us the link, we will merge it
> 
> > > 
> > 
> > 
> > Please do something for it. Merge it in source

Okah I'll Be Sending The Link Here

**Comment by RT1648** [comment]
> > Fork this repo, pick it yourself and give us the link, we will merge it
> > > > 
> > > 
> > > 
> > > Please do something for it. Merge it in source
> 
> none of our devices use that hal, so naaaaah

Pull request opened. Please check it and merge it. Thanks!
